### ISSUE TITLE
Uninstall doesn't work

### ISSUE THREAD

**Issue by danielschmalhofer** [YunoHost-Apps/roadiz_ynh#10]
after uninstalling I'm left with this error in php5-fpm:

`Mar 14 19:18:06 SERVER php5-fpm[5410]: [14-Mar-2017 19:18:06] ERROR: [pool roadiz] the chdir path '/var/www/roadiz' does not exist or is not a directory   
Mar 14 19:18:06 SERVER php5-fpm[5410]: [14-Mar-2017 19:18:06] ERROR: failed to post process the configuration                                              
Mar 14 19:18:06 SERVER php5-fpm[5410]: [14-Mar-2017 19:18:06] ERROR: FPM initialization failed                                                             
Mar 14 19:18:06 SERVER systemd[1]: php5-fpm.service: main process exited, code=exited, status=78/n/a                                                       
Mar 14 19:18:06 SERVER systemd[1]: Failed to start The PHP FastCGI Process Manager.                                                                        
Mar 14 19:18:06 SERVER systemd[1]: Unit php5-fpm.service entered failed state.          `

seems to leave some php5-fpm or nginx configs behind - they will only run if I mkdir /var/www/roadiz

**Comment by frju365** [comment]
Fixed with commit 0fe09e15175b304224475f1622cc3db9a2c0b962
