### ISSUE TITLE
admin site access

### ISSUE THREAD

**Issue by danielschmalhofer** [YunoHost-Apps/roadiz_ynh#9]
Hey there!

Installed your great plugin - and I fail to access /rz-admin

is it
https://domain.ltd/roadiz/rz-admin
or
https://domain.ltd/rz-admin
?

Both seem to fail!

Maybe it has something to do with the field on the buttom of the install form - what should I insert there?

Greetings,
Kamaluk

**Comment by frju365** [comment]
ok... in fact... the installation may fail on subdir... I will fix it this weekend. on root path, you could normally access to it. But it's better that you wait until I try this on a proper installation(Tomorrow or friday)

Thanks for your report. :)

**Comment by frju365** [comment]
Fixed with commit 9dc1b02afde79151344faa625f9f8bcb26d72d1d
